### ISSUE TITLE
No Sound on MacOS after the latest FMOD extension update (1.0.1, from November 25, 2024)

### ISSUE THREAD

**Issue by augustoescobar** [YoYoGames/GMEXT-FMOD#26]
### Description

It seems there is an issue with the latest version (1.0.1, from November 25, 2024) available on GameMaker marketplace. Sounds are working fine on Windows, but nothing plays on MacOS. My game works fine with the previous version (1.0.0). 

I can see on logs FMOD libraries are loaded as expected, no errors are thrown. The library is also correct. 

To reproduce the issue, on MacOS, create a new GameMaker project, import all FMOD components using the Marketplace, set **rm_fmod_init** as the home room and start the game.

Visually, all components are correct, but clicking on buttons plays no sound. I'm sure the API path is correct on the extension configs. 

Could you please check this? My sound artist works on a Mac and he needs this integration working. 

The FMOD API version is 2.02.26 (latest available). We tested it in both MacOS Sequoia and Monterey with no luck. Using the previous version of the extension works as expected. Our GM runtime version is 2024.6.0.205.

Thanks in advance.

### Expected Change

Sounds are playing on MacOS.

### Steps To Reproduce

1. Start a new GM project
2. Import all Fmod Ext components from the marketplace library
3. Set rm_fmod_init as the main room (home)
4. Add the FMOD library path into the fmod configs 
5. Run the project (F5)
6. Click on buttons and notice nothing is played

[gamemaker-fmod.log](https://github.com/user-attachments/files/18424906/gamemaker-fmod.log)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release

### Which platform(s) are you seeing the problem on?

macOS

### Compiler Log File

- [x] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by DiasFranciscoA** [comment]
We were not able to replicate this issue internally, we would need you to provide the full path to the SDK folder you are using and an image with the contents of that folder to verify that everything is configured correctly also would ask you to confirm that you have the signing identity filled in correctly in the projects IDE for macOS.

Note this didn't use to work because you couldn't use the extension with a VM build, now it is possible (if you are running from the macOS IDE) but the library needs to be correctly signed (which is done at build time) but it needs the signing data to be added to the IDE. You can also use the YYC which does the same thing automatically from within XCode.

**Comment by augustoescobar** [comment]
First of all, thanks for the quick response. 

As I don't intend to release the game for macOS, only running the game from the IDE is fine by me. Thus, I didn't configure the signing mechanisms as, in my understanding, it would result in developer license charges from Apple. 

Instead. I'm running the game GMS2 VM as a target output, and providing the permissions for the FMOD libraries to be executed from my system. To do that, I ran these steps: 

First, allow access to the libraries using the Private & Security section under System Settings. The, after accepting all alerts shown by macOS, navigate to the library folder and remove the libraries from the quarantine. 

> cd "~/Library/FMOD Programmers API" 
> xattr -d com.apple.quarantine ./*

As long as I'm still running the game targeting GMS2 VM as the output, this process works like. 

If you want to see my sample code, please check this link to my Drive https://drive.google.com/drive/folders/1uZqFEX3FN2DoNdf_jawYa-2uatG0D73t?usp=drive_link

**Comment by tacticaldude00** [comment]
I believe I am experiencing a similar issue. 

`bash DONE (0)
/Users/aescobar/Projects/FmodSample/extensions/FMOD/post_build_step.sh
[FMOD] INIT: Script initialization succeeded (v1.0.1 :: 1).
Copying macOS (64 bit) dependencies
error: The specified item could not be found in the keychain.
error: The specified item could not be found in the keychain.`

This seems to be the start of this issue. It shows up in my logs as well. This next snippet from his log also shows up in my logs.

`Process Chunk: SCPT   4048
Process Chunk: DBGI   44248
Process Chunk: INST   456
Process Chunk: LOCL   6088
Process Chunk: DFNC   8696
Process Chunk: STRG   237491
Reading File /tmp/GameMakerStudio2/GMS2TEMP/FmodSample_53D9296_VM/game.ios
Loaded File /tmp/GameMakerStudio2/GMS2TEMP/FmodSample_53D9296_VM/game.ios(539484)
Get Resolution
Get Header Information
InitGMLFunctions
HighScore..filename is /Users/aescobar/Library/Application Support/com.yoyogames.macyoyorunner/hiscore.dat
Game..Math..Graphic..File..Resource..Interaction..3D..Particle..Misc..Time..DS..Sound..Physics..Gamepad..Buffers..Networking..Shaders..YoYo..Multiplayer..Fini
dlopen(/tmp/GameMakerStudio2/GMS2TEMP/FmodSample_53D9296_VM/libYYFMOD.dylib) failed with error: "dlopen(@loader_path/liblibYYFMOD.dylib, 0x0001): tried: '/Users/Shared/GameMakerStudio2/Cache/runtimes/runtime-2024.6.0.205/mac/YoYo Runner.app/Contents/MacOS/liblibYYFMOD.dylib' (no such file)"
Could not find function "__libfmodL_load__" in "/tmp/GameMakerStudio2/GMS2TEMP/FmodSample_53D9296_VM/libfmodL.dylib" with argument types [].
Could not find function "__libfmodstudioL_load__" in "/tmp/GameMakerStudio2/GMS2TEMP/FmodSample_53D9296_VM/libfmodstudioL.dylib" with argument types [].
Code_Load()
VARI_Load()
ID_STRG`

I included more of the log for context. This is just what I have observed. My current theory is this has to do with key signatures on MacOS. When attempting to first launch the project, both the example and my own project, there is a Gatekeeper popup notifying that MacOS will not launch the libraries ending in .dylib. Hope this helps in any way.

**Comment by tacticaldude00** [comment]
I followed the steps to create signing certificates and it did sign the libraries. However the system still doesn't properly initialize. On further inspection It may be due to the way its building for VM. 

`Process Chunk: DFNC   8696
Process Chunk: STRG   237491
Reading File /tmp/GameMakerStudio2/GMS2TEMP/fmod_F715962_VM/game.ios
Loaded File /tmp/GameMakerStudio2/GMS2TEMP/fmod_F715962_VM/game.ios(507564)
Get Resolution
Get Header Information
InitGMLFunctions
HighScore..filename is /Users/*****/Library/Application Support/com.yoyogames.macyoyorunner/hiscore.dat
Game..Math..Graphic..File..Resource..Interaction..3D..Particle..Misc..Time..DS..Sound..Physics..Gamepad..Buffers..Networking..Shaders..YoYo..Multiplayer..Fini
dlopen(/tmp/GameMakerStudio2/GMS2TEMP/fmod_F715962_VM/libYYFMOD.dylib) failed with error: "dlopen(@loader_path/liblibYYFMOD.dylib, 0x0001): tried: '/Users/Shared/GameMakerStudio2/Cache/runtimes/runtime-2024.11.0.226/mac/YoYo Runner.app/Contents/MacOS/liblibYYFMOD.dylib' (no such file)"
Could not find function "__libfmodL_load__" in "/tmp/GameMakerStudio2/GMS2TEMP/fmod_F715962_VM/libfmodL.dylib" with argument types [].
Could not find function "__libfmodstudioL_load__" in "/tmp/GameMakerStudio2/GMS2TEMP/fmod_F715962_VM/libfmodstudioL.dylib" with argument types [].
Code_Load()
VARI_Load()`

This liblibYYFMOD.dylib file seems to be missing from builds. Perhaps here could be where the error arises?

**Comment by DiasFranciscoA** [comment]
This message is expected, because those functions don't actually exist and are only there to to flag the file as being used. Does the problem still persists though? Does sound within FMOD still fails to play? We would need a complete log of the extensions for narrowing the problem. Thank you so much for the report, we are working to solve this issue.

**Comment by tacticaldude00** [comment]
Unfortunately, audio still does not come through the FMOD audio system. The runtime and IDE I am using is the latest with this build and log. The libraries do get signed and does not cause issues with Gatekeeper. (I had even turned off Gatekeeper temporarily to test this.) Attached is a sanitized log with as minimal personal info as possible without compromising the log. If this is any help, my mac is an X86-64 iMac 2019. 

[FMOD.log](https://github.com/user-attachments/files/18528806/FMOD.log)

**Comment by tacticaldude00** [comment]
Addendum to my previous post. There is no previous version of the extension currently functional on my machine. I had also tested in my other project that was using FMOD on windows. On that version I had used the function for responding the driver the FMOD system was currently attached to. On windows it responds fine with the available driver. On mac it responds with 'undefined'. I have not tested building on mac for a different platform. I will test building on a mac for linux and test that, and respond with what I find if I can find anything.

**Comment by DiasFranciscoA** [comment]
> Unfortunately, audio still does not come through the FMOD audio system. The runtime and IDE I am using is the latest with this build and log. The libraries do get signed and does not cause issues with Gatekeeper. (I had even turned off Gatekeeper temporarily to test this.) Attached is a sanitized log with as minimal personal info as possible without compromising the log. If this is any help, my mac is an X86-64 iMac 2019.
> 
> [FMOD.log](https://github.com/user-attachments/files/18528806/FMOD.log)

The x64 bit is actually important the libraries were not being compiled with the x64 architecture which might have led to the issues you were having. We just released a new version (1.0.3) let us know if this fixed the issue (we currently don't have local x64 machines to test this with)

**Comment by tacticaldude00** [comment]
[fmod2.log](https://github.com/user-attachments/files/18542547/fmod2.log)

Tested 1.0.3. There seems to be progress but the system still does not initalize. Lots of `Could not find function`.

**Comment by DiasFranciscoA** [comment]
@tacticaldude00 thank you again for your time I would like to suggest a test to make sure we are moving in the correct path before publishing an update to the extension. Could you check if replacing the extensions `post_build_step.sh` file with the following solves the issue:

[post_build_step.zip](https://github.com/user-attachments/files/18642360/post_build_step.zip)

Steps:
1. Open your project in the file explorer
2. Go into `extensions/fmod/`
3. locate the `post_build_step.sh`
4. download the attached file (above)
5. extract the zip into the folder on step 2
6. replace the existing file there
7. Run your game

**Comment by tacticaldude00** [comment]
[fmod3.log](https://github.com/user-attachments/files/18647510/fmod3.log)
Errored in a very similar way. I apologize for the news. I greatly appreciate your patience, however, thank you!

**Comment by DiasFranciscoA** [comment]
Can you send us a copy of `libYYFMOD.dylib` please attach it here, just so that we exclude some importing issues.
Thank you so much for the time,

Francisco Dias
